#created by chase reed
language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t chasereed7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chasereed7/react-test npm test

after_success:
  - docker build -t chasereed7/multi-client ./client
  - docker build -t chasereed7/multi-nginx ./nginx
  - docker build -t chasereed7/multi-server ./server
  - docker build -t chasereed7/multi-worker ./worker
  #must log into docker hub...
  #take those images and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #to send to docker
  - docker push chasereed7/multi-client 
  - docker push chasereed7/multi-nginx  
  - docker push chasereed7/multi-server 
  - docker push chasereed7/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-239167185254
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY